name: deploy workflow
on: [push, workflow_dispatch]
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: Lint
              run: | 
                echo "Lint Job started"
                npm run lint
                echo "Lint Job completed"
    Test:
        needs: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: Test
              run: | 
                echo "Test Job Started"
                npm test
                echo "Test Job completed"
    Deploy:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: Deploy
              run: |
                echo "Deploy Job started"
                npm deploy
                echo "Deploy Job completed"

